// Initial data for Mission Control
import { Agent, Task, Activity } from './types';

export const initialAgents: Agent[] = [
  {
    id: 'jarvis',
    name: 'Jarvis',
    role: 'Squad Lead',
    status: 'active',
    emoji: '🤖',
    color: 'bg-blue-500',
    sessionKey: 'agent:main:main',
    lastHeartbeat: new Date().toISOString(),
    description: 'Coordinator. Handles direct requests, delegates, monitors progress. Primary interface.',
  },
  {
    id: 'shuri',
    name: 'Shuri',
    role: 'Product Analyst',
    status: 'idle',
    emoji: '🔍',
    color: 'bg-purple-500',
    sessionKey: 'agent:product-analyst:main',
    lastHeartbeat: new Date().toISOString(),
    description: 'Skeptical tester. Finds edge cases and UX issues. Tests competitors.',
  },
  {
    id: 'fury',
    name: 'Fury',
    role: 'Customer Researcher',
    status: 'idle',
    emoji: '📊',
    color: 'bg-red-500',
    sessionKey: 'agent:customer-researcher:main',
    lastHeartbeat: new Date().toISOString(),
    description: 'Deep researcher. Every claim comes with receipts. Reads G2 reviews for fun.',
  },
  {
    id: 'vision',
    name: 'Vision',
    role: 'SEO Analyst',
    status: 'idle',
    emoji: '👁️',
    color: 'bg-indigo-500',
    sessionKey: 'agent:seo-analyst:main',
    lastHeartbeat: new Date().toISOString(),
    description: 'Thinks in keywords and search intent. Makes sure content can rank.',
  },
  {
    id: 'loki',
    name: 'Loki',
    role: 'Content Writer',
    status: 'idle',
    emoji: '✍️',
    color: 'bg-green-500',
    sessionKey: 'agent:content-writer:main',
    lastHeartbeat: new Date().toISOString(),
    description: 'Words are his craft. Pro-Oxford comma. Anti-passive voice.',
  },
  {
    id: 'friday',
    name: 'Friday',
    role: 'Developer',
    status: 'idle',
    emoji: '⚡',
    color: 'bg-cyan-500',
    sessionKey: 'agent:developer:main',
    lastHeartbeat: new Date().toISOString(),
    description: 'Code is poetry. Clean, tested, documented.',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Set up Mission Control Dashboard',
    description: 'Create the initial dashboard with agent cards and task board',
    status: 'in_progress',
    assigneeIds: ['friday'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    comments: [
      {
        id: 'c1',
        taskId: 'task-1',
        agentId: 'jarvis',
        content: 'Let\'s build this using Next.js and shadcn/ui',
        createdAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: 'task-2',
    title: 'Research competitor pricing',
    description: 'Gather intel on competitor pricing strategies for architop.agency',
    status: 'assigned',
    assigneeIds: ['fury'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    comments: [],
  },
  {
    id: 'task-3',
    title: 'Write landing page copy',
    description: 'Draft compelling copy for architop.agency landing page',
    status: 'inbox',
    assigneeIds: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    comments: [],
  },
];

export const initialActivities: Activity[] = [
  {
    id: 'a1',
    type: 'task_created',
    agentId: 'jarvis',
    message: 'Created task: Set up Mission Control Dashboard',
    timestamp: new Date().toISOString(),
  },
  {
    id: 'a2',
    type: 'agent_status_changed',
    agentId: 'friday',
    message: 'Friday started working on dashboard setup',
    timestamp: new Date().toISOString(),
  },
];
